<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BHANU-LAPTOP" failures="1" tests="2" name="Test2" time="0.044" errors="0" timestamp="2023-05-27T11:21:22 IST">
  <testcase classname="day1.DemoB" name="testC" time="0.009"/>
  <testcase classname="day1.DemoB" name="testD" time="0.003">
    <failure type="java.lang.AssertionError" message="Something">
      <![CDATA[java.lang.AssertionError: Something
at day1.DemoB.testD(DemoB.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testD -->
</testsuite> <!-- Test2 -->
